### ISSUE TITLE
replace ugly cubes 

### ISSUE THREAD

**Issue by JuliaSchneider01** [zaryar/AquaDefender#150]
schön ist was anderes

**Comment by KozlowskiXY** [comment]
Geht es um die roten Targets? Die sind nur zu Testzwecken da, können/sollten, wenn nicht mehr gebraucht, einfach entfernt werden.

**Comment by JuliaSchneider01** [comment]
Und die grünen, die sollte man glaub nicht löschen sondern ersetzen damit die hidden enemies sich verstecken können

**Comment by KozlowskiXY** [comment]
Ok, ja, dann brauchen wir irgendeinen Busch/Pflanze/Stein oä, um das zu ersetzen.
